name: build azul_prime

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - azul-prime/**

permissions:
  actions: read
  packages: write

concurrency:
  group: azul-prime-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "pterodactyl-image-prime:azul_${{ matrix.tag }}_prime"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 17
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v3

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: "v0.10.4"
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./azul-prime
          file: ./azul-prime/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/calosis/pterodactyl-image-prime:azul_${{ matrix.tag }}_prime
